language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview

script:
  - cargo test -- --test-threads=1
  - cargo clippy

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-D warnings"

branches:
  only:
  - gh-pages
  - /.*/
